DROP table 
-- Create table for EMPLOYEE
CREATE TABLE EMPLOYEE (
    FNAME VARCHAR(50) NOT NULL,
    MINIT CHAR(1),
    LNAME VARCHAR(50) NOT NULL,
    SSN CHAR(9) PRIMARY KEY,
    BDATE DATE,
    ADDRESS VARCHAR(255),
    SEX CHAR(1),
    SALARY DECIMAL(10, 2),
    SUPERSSN CHAR(9),
    DNO INT,
 
);

-- Create table for DEPARTMENT
CREATE TABLE DEPARTMENT (
    DNAME VARCHAR(50) NOT NULL,
    DNUMBER INT PRIMARY KEY,
    MGRSSN CHAR(9),
    MGRSTARTDATE DATE,
    
);

-- Create table for DEPT_LOCATIONS
CREATE TABLE DEPT_LOCATIONS (
    DNUMBER INT,
    DLOCATION VARCHAR(50),
    PRIMARY KEY (DNUMBER, DLOCATION),
    
);

-- Create table for PROJECT
CREATE TABLE PROJECT (
    PNAME VARCHAR(50) NOT NULL,
    PNUMBER INT PRIMARY KEY,
    PLOCATION VARCHAR(50),
    DNUM INT,
    
);

-- Create table for WORKS_ON
CREATE TABLE WORKS_ON (
    ESSN CHAR(9),
    PNO INT,
    HOURS DECIMAL(4, 2),
    PRIMARY KEY (ESSN, PNO),
    
);

-- Create table for DEPENDENT
CREATE TABLE DEPENDENT (
    ESSN CHAR(9),
    DEPENDENT_NAME VARCHAR(50),
    SEX CHAR(1),
    BDATE DATE,
    RELATIONSHIP VARCHAR(25),
    PRIMARY KEY (ESSN, DEPENDENT_NAME),
    
);


